modLoader="javafml"
loaderVersion="[${forge_loader_version},)"
license="${mod_license}"

[[mods]]
modId="carianstyle"
version="${version}"
displayName="${mod_name}"
updateJSONURL="https://www.curseforge.com/minecraft/mc-mods/carianstyle"
displayURL="https://www.curseforge.com/minecraft/mc-mods/carianstyle"
logoFile="logo.png"
credits=""
authors="${mod_author}"
description='''
Carian Style!
'''

[[dependencies.carianstyle]]
modId="forge"
mandatory=true
versionRange="[${forge_loader_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.carianstyle]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"